/* ═══════════════════════════════════════════════════════════════
   sampleTestimonials.js — JARVIA 후기 샘플 라이브러리
   ─────────────────────────────────────────────────────────────
   • 6 카테고리 30개 (inheritance6 · life_insurance5 · tax5 ·
     retirement5 · corporate_ceo5 · real_estate4)
   • 각 후기는 content (200자내) · author (20자내) · meta (30자내)
   • 마스킹 형식: 성+가운데+`*` (예: 김나*, 박지*, 홍길*)
   • 컨설턴트가 라이브러리에서 클릭 → 폼에 자동 입력 → 수정 후 등록
   ═══════════════════════════════════════════════════════════════ */
window.SAMPLE_TESTIMONIALS=[
  /* ── 🏛 상속·증여 (6) ── */
  {id:'st-01', category:'inheritance', categoryLabel:'상속·증여',
    content:'이OO 팀장님 덕분에 사전증여로 상속세 7천만원 절감했습니다. 부동산이 대부분이라 막막했는데 종신보험까지 함께 설계해주셔서 자녀들이 부담 없이 자산을 받게 됐어요.',
    author:'김나* 대표', meta:'제조업, 60대'},
  {id:'st-02', category:'inheritance', categoryLabel:'상속·증여',
    content:'가업승계 컨설팅으로 예상 상속세 4억이 1억 8천만원까지 줄었습니다. 자녀에게 회사를 안전하게 물려줄 수 있게 된 점이 가장 큰 수확입니다.',
    author:'박지* 대표', meta:'중소기업, 50대'},
  {id:'st-03', category:'inheritance', categoryLabel:'상속·증여',
    content:'종신보험 + 사전증여 조합으로 자녀들이 부동산을 매각하지 않고 그대로 승계할 수 있게 됐습니다. 10년 분산 설계가 핵심이었어요.',
    author:'이서* 대표', meta:'서비스업, 60대'},
  {id:'st-04', category:'inheritance', categoryLabel:'상속·증여',
    content:'결혼하는 딸에게 증여공제 1억을 활용해 5천만원 절세했습니다. 혼인신고 2년 기한 내에 챙겨야 한다는 걸 알려주셔서 정말 다행이었어요.',
    author:'최민* 부장', meta:'회사원, 50대'},
  {id:'st-05', category:'inheritance', categoryLabel:'상속·증여',
    content:'부모님 부동산 사전증여 10년 분산 설계로 향후 상속세를 절반 가까이 줄였습니다. 일찍 시작하길 정말 잘했다는 생각이 듭니다.',
    author:'정현* 원장', meta:'전문직, 50대'},
  {id:'st-06', category:'inheritance', categoryLabel:'상속·증여',
    content:'외할머니 상속재산 정리하면서 가입돼 있던 보험금까지 청구해주셨어요. 6개월 신고 기한도 지킬 수 있게 일정 잡아주셔서 가산세 폭탄 피했습니다.',
    author:'강수* 님', meta:'개인, 40대'},
  /* ── 🛡 종신·생명보험 (5) ── */
  {id:'st-07', category:'life_insurance', categoryLabel:'종신·생명보험',
    content:'종신보험으로 상속세 납부재원 1억 5천만원을 확보했습니다. 자녀들이 급매로 부동산 처분할 일 없도록 미리 준비할 수 있어 마음이 든든해요.',
    author:'윤재* 대표', meta:'자영업, 50대'},
  {id:'st-08', category:'life_insurance', categoryLabel:'종신·생명보험',
    content:'변액유니버셜 한 상품으로 노후자금 + 보장 + 절세 3가지를 동시에 해결했습니다. 보험 하나하나 가입할 필요가 없어서 관리도 편하고요.',
    author:'한지* 사장', meta:'자영업, 50대'},
  {id:'st-09', category:'life_insurance', categoryLabel:'종신·생명보험',
    content:'갱신형 실손에서 비갱신형으로 전환해주셔서 노후 보험료 부담이 사라졌습니다. 60대 진입 전에 갈아탄 게 신의 한 수였어요.',
    author:'서영* 부장', meta:'회사원, 60대'},
  {id:'st-10', category:'life_insurance', categoryLabel:'종신·생명보험',
    content:'정기보험에서 종신보험으로 전환할 적기를 정확히 짚어주셨어요. 건강할 때 진단·인수 조건이 좋아 보험료도 합리적으로 책정됐습니다.',
    author:'임준* 대표', meta:'제조업, 40대'},
  {id:'st-11', category:'life_insurance', categoryLabel:'종신·생명보험',
    content:'보험금 수익자를 자녀로 변경해주신 덕분에 상속세 1억원 절감 효과를 봤습니다. 단순한 변경 하나로 이런 결과가 나올 줄 몰랐어요.',
    author:'배소* 님', meta:'개인, 60대'},
  /* ── 📑 세무 (종소세·법인세) (5) ── */
  {id:'st-12', category:'tax', categoryLabel:'세무',
    content:'노란우산공제 + 종신보험 조합으로 연 1,840만원 절세했습니다. 매년 5월마다 종소세 폭탄에 시달렸는데 이제 마음 편하게 사업합니다.',
    author:'박지* 대표', meta:'도소매업, 50대'},
  {id:'st-13', category:'tax', categoryLabel:'세무',
    content:'부가세 환급 누락분을 꼼꼼히 찾아주셔서 한 번에 2,300만원 환급받았습니다. 그동안 놓쳤던 매입세액공제까지 정리되니 속이 다 시원해요.',
    author:'고은* 사장', meta:'자영업, 40대'},
  {id:'st-14', category:'tax', categoryLabel:'세무',
    content:'프리랜서 첫 종합소득세 신고 컨설팅 받았어요. 가산세 폭탄 피하고 경비 처리 노하우까지 배워서 다음 해부터는 직접 준비할 수 있게 됐습니다.',
    author:'송예* 작가', meta:'프리랜서, 30대'},
  {id:'st-15', category:'tax', categoryLabel:'세무',
    content:'임대소득 분리과세 vs 종합과세 비교 분석으로 매년 200만원 이상 절세하고 있습니다. 단순한 선택 하나가 이렇게 큰 차이를 만들 줄 몰랐어요.',
    author:'노재* 님', meta:'개인, 60대'},
  {id:'st-16', category:'tax', categoryLabel:'세무',
    content:'양도세 1세대1주택 비과세 요건을 정확히 맞춰 양도세 0원으로 매각했습니다. 보유·거주 기간 체크 안 했으면 수천만원 낼 뻔했어요.',
    author:'조민* 차장', meta:'회사원, 40대'},
  /* ── 🌅 은퇴·연금 (5) ── */
  {id:'st-17', category:'retirement', categoryLabel:'은퇴·연금',
    content:'퇴직 시점에 IRP로 옮겨두라는 조언 덕분에 퇴직소득세를 절반으로 줄였습니다. 60일 안에 처리 안 했으면 큰일 날 뻔했어요.',
    author:'이서* 부장', meta:'회사원, 50대'},
  {id:'st-18', category:'retirement', categoryLabel:'은퇴·연금',
    content:'연금저축 + IRP 합산 900만원 세액공제 매년 챙기고 있습니다. 환급액으로 다시 재투자 사이클이 만들어져서 노후 준비가 가속됐어요.',
    author:'권나* 과장', meta:'회사원, 40대'},
  {id:'st-19', category:'retirement', categoryLabel:'은퇴·연금',
    content:'국민연금 임의가입 컨설팅 받아 노후 월 30만원을 추가로 확보하게 됐습니다. 50대 늦깎이라도 늦지 않다는 걸 알려주셔서 감사해요.',
    author:'문영* 님', meta:'주부, 50대'},
  {id:'st-20', category:'retirement', categoryLabel:'은퇴·연금',
    content:'변액연금에서 즉시연금으로 전환 타이밍을 잡아주셔서 종신수령 시작했습니다. 매월 안정적 현금흐름이 생기니 노후가 한결 든든해요.',
    author:'홍기* 님', meta:'개인, 60대'},
  {id:'st-21', category:'retirement', categoryLabel:'은퇴·연금',
    content:'노후 4층 연금 설계 (국민·퇴직·개인·주택연금)로 은퇴 후에도 월 400만원 이상 현금흐름 확보했습니다. 든든한 미래가 그려져요.',
    author:'유성* 차장', meta:'회사원, 50대'},
  /* ── 🏢 법인 CEO (가지급금·퇴직금) (5) ── */
  {id:'st-22', category:'corporate_ceo', categoryLabel:'법인 CEO',
    content:'법인 가지급금 4억을 안전하게 정리했습니다. 인정상여 위험에서 벗어나고 세무조사 걱정도 사라졌어요. 매출 30억대 법인 대표라면 꼭 한번 받아보시길.',
    author:'최민* 대표', meta:'서비스업, 50대'},
  {id:'st-23', category:'corporate_ceo', categoryLabel:'법인 CEO',
    content:'CEO 퇴직금 한도 설계로 세후 2억원을 더 받게 됐습니다. 정관 정비 + 퇴직금 규정 신설이 핵심이었어요. 미리 준비 안 했으면 못 받았을 금액입니다.',
    author:'김태* 대표', meta:'제조업, 60대'},
  {id:'st-24', category:'corporate_ceo', categoryLabel:'법인 CEO',
    content:'임원 보수·배당·퇴직금 최적 조합 설계로 연간 절세액이 3천만원을 넘었습니다. 단순히 월급만 받던 시절과는 완전히 달라요.',
    author:'장동* 대표', meta:'IT, 40대'},
  {id:'st-25', category:'corporate_ceo', categoryLabel:'법인 CEO',
    content:'비상장주식 평가 컨설팅으로 가업승계 준비 완료했습니다. 5년 후 자녀에게 회사를 넘길 때 세금이 어느 정도 들지 미리 알 수 있어 든든해요.',
    author:'한경* 대표', meta:'제조업, 50대'},
  {id:'st-26', category:'corporate_ceo', categoryLabel:'법인 CEO',
    content:'직무발명보상금 제도로 법인세 + 종소세 동시 절감 효과를 봤습니다. 매년 합법적으로 수천만원이 절세되니 사업이 한층 안정됐어요.',
    author:'오현* 대표', meta:'제조업, 50대'},
  /* ── 🏠 부동산·자산관리 (4) ── */
  {id:'st-27', category:'real_estate', categoryLabel:'부동산·자산',
    content:'일시적 1세대2주택 비과세 요건을 정확히 맞춰서 양도세 0원으로 매각했습니다. 신·구주택 보유 기간 체크 안 했으면 8천만원 낼 뻔했어요.',
    author:'심혜* 부장', meta:'회사원, 40대'},
  {id:'st-28', category:'real_estate', categoryLabel:'부동산·자산',
    content:'임대사업자 등록 컨설팅으로 종부세 부담이 크게 줄었습니다. 등록 시점·세제 혜택까지 종합 검토해주셔서 매년 절세 효과 누리고 있어요.',
    author:'백지* 님', meta:'개인, 50대'},
  {id:'st-29', category:'real_estate', categoryLabel:'부동산·자산',
    content:'개인 명의 부동산을 법인 명의로 이전하면서 절세 효과를 극대화했습니다. 임대수익에 대한 세부담이 절반 이하로 떨어졌어요.',
    author:'전성* 대표', meta:'자영업, 60대'},
  {id:'st-30', category:'real_estate', categoryLabel:'부동산·자산',
    content:'상가 양도 시점을 1년 조정해서 양도세를 7천만원 줄였습니다. 단순히 매수자 잡힐 때 파는 게 아니라 세금 시점까지 봐야 한다는 걸 배웠어요.',
    author:'안지* 님', meta:'개인, 60대'}
];
